# Generated by Django 6.1.1 on 2026-09-12 19:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_stripe_payment_intent_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Запитання')),
                ('answer', models.TextField(verbose_name='Відповідь')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='Категорія')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'База знань FAQ',
                'verbose_name_plural': 'База знань FAQ',
                'ordering': ('category', 'question'),
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID сесії')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сесії гостя')),
                ('status', models.CharField(choices=[('ACTIVE', 'Активна'), ('ESCALATED', 'Ескальована'), ('RESOLVED', 'Завершена')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Статус')),
                ('is_escalated', models.BooleanField(db_index=True, default=False, verbose_name='Ескальовано на оператора')),
                ('escalation_reason', models.TextField(blank=True, verbose_name='Причина ескалації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Сесія чату',
                'verbose_name_plural': 'Сесії чату',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('assistant', 'Асистент'), ('tool', 'Інструмент'), ('system', 'Система')], max_length=20, verbose_name='Роль')),
                ('content', models.TextField(blank=True, verbose_name='Вміст повідомлення')),
                ('tool_calls', models.JSONField(blank=True, null=True, verbose_name='Виклики інструментів')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.chatsession', verbose_name='Сесія чату')),
            ],
            options={
                'verbose_name': 'Повідомлення чату',
                'verbose_name_plural': 'Повідомлення чату',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон клієнта')),
                ('reason', models.CharField(choices=[('COMPLAINT', 'Скарга'), ('ORDER_ISSUE', 'Проблема із замовленням'), ('HUMAN_REQUESTED', 'Запит людини'), ('BOT_CONFUSED', 'Бот не зрозумів')], default='HUMAN_REQUESTED', max_length=50, verbose_name='Причина звернення')),
                ('details', models.TextField(blank=True, verbose_name='Деталі звернення')),
                ('status', models.CharField(choices=[('OPEN', 'Відкрито'), ('IN_PROGRESS', 'В обробці'), ('RESOLVED', 'Вирішено')], db_index=True, default='OPEN', max_length=20, verbose_name='Статус тікета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Вирішено о')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='orders.order', verbose_name='Замовлення')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='support.chatsession', verbose_name='Сесія чату')),
            ],
            options={
                'verbose_name': 'Тікет підтримки',
                'verbose_name_plural': 'Тікети підтримки',
                'ordering': ('-created_at',),
            },
        ),
    ]
