# Generated by Django 6.1.1 on 2026-09-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('display_order', 'name'), 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('title',), 'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterModelOptions(
            name='dishoption',
            options={'ordering': ('dish', 'price_delta', 'name'), 'verbose_name': 'Опція страви', 'verbose_name_plural': 'Опції страв'},
        ),
    ]
