# Generated by Django 6.1.1 on 2026-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_alter_dish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='dishes/', verbose_name='Зображення'),
        ),
    ]
