# Generated by Django 6.1.1 on 2026-09-11 12:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_alter_category_options_alter_dish_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сесії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Кошик',
                'verbose_name_plural': 'Кошики',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Кількість')),
                ('selected_options', models.JSONField(blank=True, default=list, verbose_name='Обрані опції')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='Кошик')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='menu.dish', verbose_name='Страва')),
            ],
            options={
                'verbose_name': 'Позиція кошика',
                'verbose_name_plural': 'Позиції кошика',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='Номер замовлення')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Ключ сесії гостя')),
                ('customer_name', models.CharField(max_length=100, verbose_name="Ім'я клієнта")),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клієнта')),
                ('delivery_address', models.TextField(verbose_name='Адреса доставки')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує оплати'), ('PAID', 'Оплачено'), ('PREPARING', 'Готується на кухні'), ('ON_WAY', "Кур'єр у дорозі"), ('DELIVERED', 'Доставлено'), ('CANCELLED', 'Скасовано')], db_index=True, default='PENDING', max_length=20, verbose_name='Статус замовлення')),
                ('payment_method', models.CharField(choices=[('CARD', 'Картка'), ('CASH', 'Готівка')], default='CARD', max_length=10, verbose_name='Спосіб оплати')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Очікує оплати'), ('COMPLETED', 'Оплачено')], default='PENDING', max_length=20, verbose_name='Статус оплати')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Загальна сума (грн)')),
                ('eta_minutes', models.PositiveIntegerField(default=30, verbose_name='Орієнтовний час доставки (хв)')),
                ('notes', models.TextField(blank=True, verbose_name='Коментар до замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_title', models.CharField(max_length=200, verbose_name='Назва страви (снапшот)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна (снапшот, грн)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('selected_options', models.JSONField(blank=True, default=list, verbose_name='Обрані опції (снапшот)')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='menu.dish', verbose_name='Страва')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Позиція замовлення',
                'verbose_name_plural': 'Позиції замовлення',
            },
        ),
    ]
