# Generated by Django 6.1.1 on 2026-09-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID платежу Stripe (PaymentIntent)'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID сесії Stripe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Оплата онлайн (Stripe)'), ('STRIPE', 'Картка онлайн (Stripe)'), ('CARD', 'Картка'), ('CASH', 'Готівка')], default='CARD', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Очікує оплати'), ('PAID', 'Оплачено'), ('COMPLETED', 'Оплачено'), ('FAILED', 'Помилка оплати'), ('REFUNDED', 'Повернено')], default='PENDING', max_length=20, verbose_name='Статус оплати'),
        ),
    ]
